/* tslint:disable:max-line-length */
export default {
    name: "ifttt",
    config: {
        cacheDir: `cache`,
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
    },
    message: {
        argv: {
            describe: {
                command: {
                    $0: "Control IFTTT from the command line.",
                    login: "Log in to IFTTT.\nIf the option is omitted, please log in from the launched browser.",
                    logout: "Log out of IFTTT.",
                    connect: "Connect to the specified service.",
                    list: "Display a list of applets.\nUse the `-l, --long` option to display the details.",
                    get: "Get the applet recipe.\nThe recipe of all applets is acquired by specifying `-a, -all` option.",
                    create: "Create the applet.\nSpecify and execute a JSON file containing a recipe.",
                    delete: "Remove the applet.\nSpecify the ID of the applet you want to delete and execute it.",
                    update: "Update the applet.\nSpecify and execute a JSON file containing a recipe.",
                },
                positional: {
                    mailAddress: "Please specify your login email address.",
                    password: "Please specify a login password.",
                    loginId: "IMPL: implement!",
                    service: "Please specify a service ID.",
                    id: "Specifies the applet's ID.\nMultiple IDs can be specified.",
                    file: "Specify a JSON file that contains the applet recipe.",
                },
                option: {
                    browser: "Control while displaying chrome.",
                    email: "Login with Email and Password.\nPlease specify your login email address and password following options.",
                    google: "Log in with Google account.",
                    facebook: "Log in with Facebook account.",
                    long: "Display detailed information.",
                    all: "Get all applet recipes.",
                },
            },
            error: {
                mailAddress: "Error: E-mail address format is invalid!",
                password: "Error: Password must be at least 6 characters!",
                file: "Error: File not found!",
                get: "Error: Specify the applet ID for which you want to get the recipe, or the `-a, -all` option!",
            },
        },
        command: {
            success: {
                login: "Logged in!",
                logout: "Logged out!",
                connect: "Connected!",
                create: "Create applet: ",
                delete: "Delete applet: ",
                update: "Update applet: ",
                createComplate: "Create is complete!",
                deleteComplate: "Delete is complete!",
                updateComplate: "Update is complete!",
            },
            error: {
                loggedIn: "Error: Already logged in!",
                notLoggedIn: "Error: Not logged in!",
                loginFailed: "Error: Login failed!",
                serviceNotFound: "Error: Not Found the service to connect!",
                connectionFailed: "Error: Connection failed!",
                connected: "Error: Already connected!",
                needConnect: "Error: You need a service connection!\nPlease execute command with `ifttt connect ",
                noApplet: "Error: There is no applet!",
                appletNotFound: "Error: The applet with the specified ID can not be found!",
                serviceDataNotFound: "Error: The service data could not be found!",
                serviceIdNotFound: "Error: The service with the specified ID can not be found!",
                serviceTypeNotFound: "Error: Could not find the specified type of service!",
                serviceField: "Error: The specified input field can not be found!",
                serviceFieldType: "Error: The specified input field type can not be found!",
                serviceSelectField: "Error: The value of the specified select box can not be found!",
                notCreate: "Error: Could not create applet!",
                notUpdate: "Error: Could not update applet!",
                updateServiceNotMatch: "Error: Update target service does not match!",
            },
        },
    },
    url: {
        root: "https://ifttt.com/",
        join: "https://ifttt.com/join",
        login: "https://ifttt.com/login",
        myApplets: "https://ifttt.com/my_applets",
        create: "https://ifttt.com/create",
        discover: "https://ifttt.com/discover",
    },
    ifttt: {
        fieldType: {
            text: "text_field",
            select: "collection_select",
        },
    },
}
